/* Authored by Chubak Bidpaa: chubakbidpaa@gmail.com - 2020 - Corona Times */

export const FETCH_RESUME = 'FETCH_RESUME';
export const SET_CREATION_INFO = 'SET_CREATION_INFO';
export const SET_CONTACT_INFO = 'SET_CONTACT_INFO';
export const SET_SUMMARY_OBJECTIVE = 'SET_SUMMARY_OBJECTIVE';
export const APPEND_HISTORY = 'APPEND_HISTORY';
export const APPEND_SKILLS = 'APPEND_SKILLS';
export const APPEND_SOFTWARE = 'APPEND_SOFTWARE';
export const APPEND_DEGREES = 'APPEND_DEGREES';
export const APPEND_CERTS = 'APPEND_CERTS';
export const APPEND_AWARDS = 'APPEND_AWARDS';
export const APPEND_VOLUNTEERING = 'APPEND_VOLUNTEERING';
export const RESTORE_TO_CAPTURE = 'RESTORE_TO_CAPTURE';
